programs:
  - name: Die Anstalt
    min-length: 20
    season-offset: 2013
    max-age: 200
    station: zdf
  - name: Suits
    station: zdfneo
    min-length: 30
    all-pages: True
  - name: Mad Men
    min-length: 30
    station: arte.de
    all-pages: True
  - name: Wolf Hall
    min-length: 40
    station: arte.de
  - name: The Rookie
    min-length: 30
    station: zdfneo
    all-pages: True
  - name: 'Der Herr der Ringe: Die Ringe der Macht'
    station: zdfneo
    min-length: 45
    all-pages: True
  - name: 'Agatha Christies Marple'
    station: one
    min-length: 60
